openapi: 3.0.0
info:
  title: Todo App - Tasks API
  description: Task management endpoints with JWT authentication
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/tasks:
    get:
      summary: List tasks
      description: Get all tasks for authenticated user with optional filtering
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, in_progress, completed]
          description: Filter by task status
        - name: due_date
          in: query
          schema:
            type: string
            format: date-time
          description: Filter by due date (ISO 8601)
        - name: sort
          in: query
          schema:
            type: string
            enum: [created_at, due_date, title]
            default: created_at
          description: Sort field
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort order
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Pagination limit
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Pagination offset
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      tasks:
                        type: array
                        items:
                          $ref: '#/components/schemas/Task'
                      total:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 50
                      offset:
                        type: integer
                        example: 0
                  message:
                    type: string
                    nullable: true
                    example: null
                  errors:
                    type: array
                    nullable: true
                    example: null
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create task
      description: Create a new task for authenticated user
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  example: Complete project
                description:
                  type: string
                  maxLength: 2000
                  nullable: true
                  example: Finish Phase II implementation
                status:
                  type: string
                  enum: [pending, in_progress, completed]
                  default: pending
                  example: pending
                due_date:
                  type: string
                  format: date-time
                  nullable: true
                  example: "2026-01-15T00:00:00Z"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      task:
                        $ref: '#/components/schemas/Task'
                  message:
                    type: string
                    example: Task created successfully
                  errors:
                    type: array
                    nullable: true
                    example: null
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/tasks/{id}:
    get:
      summary: Get task
      description: Get a specific task by ID
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
          example: tsk_1234567890
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      task:
                        $ref: '#/components/schemas/Task'
                  message:
                    type: string
                    nullable: true
                    example: null
                  errors:
                    type: array
                    nullable: true
                    example: null
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update task
      description: Update entire task (all fields)
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
          example: tsk_1234567890
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - status
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  example: Complete project (updated)
                description:
                  type: string
                  maxLength: 2000
                  nullable: true
                  example: Finish Phase II implementation and testing
                status:
                  type: string
                  enum: [pending, in_progress, completed]
                  example: in_progress
                due_date:
                  type: string
                  format: date-time
                  nullable: true
                  example: "2026-01-16T00:00:00Z"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      task:
                        $ref: '#/components/schemas/Task'
                  message:
                    type: string
                    example: Task updated successfully
                  errors:
                    type: array
                    nullable: true
                    example: null
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Partial update task
      description: Update specific fields of a task
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
          example: tsk_1234567890
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  example: Complete project (updated)
                description:
                  type: string
                  maxLength: 2000
                  nullable: true
                  example: Updated description
                status:
                  type: string
                  enum: [pending, in_progress, completed]
                  example: completed
                due_date:
                  type: string
                  format: date-time
                  nullable: true
                  example: "2026-01-17T00:00:00Z"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      task:
                        $ref: '#/components/schemas/Task'
                  message:
                    type: string
                    example: Task updated successfully
                  errors:
                    type: array
                    nullable: true
                    example: null
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete task
      description: Delete a task permanently
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
          example: tsk_1234567890
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    nullable: true
                    example: null
                  message:
                    type: string
                    example: Task deleted successfully
                  errors:
                    type: array
                    nullable: true
                    example: null
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth (7-day expiry)

  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Task unique identifier
          example: tsk_1234567890
        title:
          type: string
          description: Task title
          example: Complete project
        description:
          type: string
          nullable: true
          description: Task description
          example: Finish Phase II implementation
        status:
          type: string
          enum: [pending, in_progress, completed]
          description: Task status
          example: in_progress
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Task due date
          example: "2026-01-15T00:00:00Z"
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2026-01-07T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-01-07T12:00:00Z"
      required:
        - id
        - title
        - status
        - created_at
        - updated_at

    ErrorDetail:
      type: object
      properties:
        field:
          type: string
          example: title
          description: Field name with validation error
        message:
          type: string
          example: Title is required
          description: Error message
      required:
        - field
        - message

  responses:
    Unauthorized:
      description: Unauthorized - Invalid or missing JWT token
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              data:
                type: object
                nullable: true
                example: null
              message:
                type: string
                example: Invalid or missing authentication token
              errors:
                type: array
                nullable: true
                example: null

    Forbidden:
      description: Forbidden - Task belongs to different user
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              data:
                type: object
                nullable: true
                example: null
              message:
                type: string
                example: You don't have permission to access this task
              errors:
                type: array
                nullable: true
                example: null

    NotFound:
      description: Task not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              data:
                type: object
                nullable: true
                example: null
              message:
                type: string
                example: Task not found
              errors:
                type: array
                nullable: true
                example: null

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              data:
                type: object
                nullable: true
                example: null
              message:
                type: string
                example: Validation failed
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorDetail'
                example:
                  - field: title
                    message: Title is required
